### ISSUE TITLE
How to train with 50k documents? Now, it's impossible?

### ISSUE THREAD

**Issue by onepiecehung** [stanleyfok/content-based-recommender#2]
I'm try training with 50.000 documents, but it's got too many ram? And Node.js heap out of memory, (10k docs ~ 2GB RAM)

So, how can I fix it?

This NPM: https://github.com/guymorita/recommendationRaccoon, save the result to Redis, you can save the result in Redis, and for high performance?

**Comment by stanleyfok** [comment]
Thanks for your feedback. I write it more for a prove of concept. So I did not try to run it with high amount of documents :) I believe much to do to improve this. I will try my best when I get some time.

**Comment by stanleyfok** [comment]
closing this issue as no plan yet.
